Hello-Kitchen/POS-Front-End

- src/Components/CurrentCommand/CurrentCommand.js
> 39-gestion-des-commandes-vide

- README.md
- package-lock.json
- package.json
- src/Pages/Loading/Loading.js
- src/Pages/Login/Login.js
POS can now handle the JWT given by the back
Closes #44 
> feat: Handling of the JWT given from back

- src/Pages/Loading/Loading.js
- src/Pages/Login/Login.js
The login page can display error messages when bad credentials are given or if the user needs to log again
Closes #46 
> feat: error modal in loading page

- src/Components/FoodElem/DetailList/DetailList.js
> fix: changed typo (multiple from mutliple) inside the details of a food

- .babelrc
- eslint.config.mjs
- package-lock.json
- package.json
- src/Components/CurrentCommand/CurrentCommand.js
- src/Pages/Layout.js
- src/__tests__/Components/Calculator.test.js
- src/__tests__/Components/CategoryButton.test.js
- src/__tests__/Components/CurrentCommand.test.js
- src/__tests__/Components/FoodButton.test.js
- src/__tests__/Components/FoodElem/DetailList.test.js
- src/__tests__/Components/FoodElem/FoodDetail.test.js
- src/__tests__/Components/FoodElem/FoodFooter.test.js
- src/__tests__/Components/FoodElem/FoodHeader.test.js
- src/__tests__/Components/FoodElem/IngredientList.test.js
- src/__tests__/Components/FoodElem/IngredientsButton.test.js
- src/__tests__/Components/FoodElem/ModifBackButton.test.js
- src/__tests__/Components/FoodElem/ModifButton.test.js
- src/__tests__/Components/FoodElem/__snapshots__/ModifBackButton.test.js.snap
- src/__tests__/Components/FoodElem/__snapshots__/ModifButton.test.js.snap
- src/__tests__/Components/FoodStick.test.js
- src/__tests__/Components/FooterButton.test.js
- src/__tests__/Components/LayoutFooter.test.js
- src/__tests__/Components/LayoutHeader.test.js
- src/__tests__/Components/ModsPay.test.js
- src/__tests__/Components/OptionsPay.test.js
> 51 test unitairefonctionnelperformance front pos

- src/Pages/Dashboard/Dashboard.js
Categories and foods are loaded dynamically, compared with the cache and the cache is modified accordingly.
Closes #49 
> feat: dynamic loading of categories and foods

- src/Components/CurrentCommand/CurrentCommand.js
- src/Components/FoodElem/FoodFooter/FoodFooter.js
- src/Components/FoodElem/Ingredientlist/IngredientList.js
> add: base of note button integration

- src/Components/CategoryButton/CategoryButton.js
- src/Components/FoodButton/FoodButton.js
- src/Components/FoodList/FoodList.js
- src/Components/FoodList/FoodListHeader.js
- src/Pages/Dashboard/Dashboard.js
- src/__tests__/Components/FoodListHeader.test.js
Added a header in food category with a back button
Closes #75 
> feat: header with back button in a food category

- src/Components/CurrentCommand/CurrentCommand.js
- src/Components/FoodElem/FoodFooter/FoodFooter.js
- src/Pages/Layout.js
- src/Pages/PosRouter.js
- src/__tests__/Components/CurrentCommand.test.js
Orders already existing can be edited
1. Select an order from the orders tab
2. Add a new food
3. Send the edited order
4. Select another order from the orders tab (to clear the selected order)
5. Select again the first order edited, food added should appear
Closes #81 
> feat: edit orders already existing

- src/Components/MenuListLine/MenuListLine.js
- src/Pages/Layout.js
- src/Pages/Manager/ManagerView.js
- src/__tests__/Components/MenuListLine.test.js
- src/__tests__/ManagerView.test.js
Added to the base layout of the manager menu
Log and go to Gestion tab
Switch from the manager menu to the regular menu
Closes #112 
> feat: manager view

- src/Components/LayoutHeader/LayoutHeader.js
- src/Pages/Layout.js
- src/Pages/Login/Login.js
- src/__tests__/Components/LayoutHeader.test.js
The correct ID and names of the user is displayed in the header
Log and check for informations to be displayed (for zzz user it should be 000 - Etienne Tasse)
Closes #115 
> feat: display correct name and ID in header

- src/Components/Buttons/GenericButton.js
- src/Pages/Manager/AccountManagement.js
- src/Pages/Manager/ManagerHeader.js
- src/Pages/Manager/ManagerView.js
- src/__tests__/AccountManagement.test.js
- src/__tests__/Components/GenericButton.test.js
- src/__tests__/Components/ManagerHeader.test.js
Added the account management view with logout
Log and go to Gestion>Gestion du compte
Check the correct information and logout. Access token should be deleted.
Closes #105 
> feat: Added account management view

- package-lock.json
- src/Components/CurrentCommand/CurrentCommand.js
send price of each food to one order when is created
create one order, and check in the network the payload of the request if the price of each food is send. Its ok if the request return 404 because the DTO into back was not modified !
#122 
> send price of food

- src/Components/FoodElem/FoodDetail/FoodDetail.js
- src/__tests__/Components/FoodElem/FoodDetail.test.js
update item name mapping in FoodDetail component
Display the details of a any food (if it appears, then it works)
Closes #133 
> fix: update item name mapping in FoodDetail component

- src/Pages/Dashboard/Dashboard.js
Food and category updates dynamicaly when the content edited in the DB
Log and got to dashboard
Change the category name in the DB and reresh the component (click twice on gestion for instance)
Open a category and change the name of the food in the DB. Close and open the category again.
Closes #130
> fix: correct food and category matching logic in Dashboard component

- src/Components/FoodElem/FoodDetail/FoodDetail.js
- src/Components/FoodElem/Ingredientlist/IngredientList.js
- src/__tests__/Components/FoodElem/IngredientList.test.js
Fixed the various bugs in the details and ingredients pages
The pages should be back to previous states, functionning properly.
closes #135 
> fix: detail persistence and ingredient render

- package-lock.json
- package.json
- src/Components/Calculator/Calculator.js
- src/Components/CurrentCommand/CurrentCommand.js
- src/Components/LayoutFooter/LayoutFooter.js
- src/Components/LayoutFooter/ModalNewOrder.js
- src/Components/ModsPay/ModsPay.js
- src/Components/OrdersView/OrdersView.js
- src/Pages/Dashboard/Dashboard.js
- src/Pages/Layout.js
- src/Pages/Pay/Pay.js
- src/Pages/PosRouter.js
- src/__tests__/Components/LayoutFooter.test.js
- src/__tests__/Components/ModsPay.test.js
- src/setupTests.js
Add call api for update order payment details + stock the order id when id created
Created a new order, send the first part and close the payment.
#136 
Before check this PR, accept and merge the PR number #127 into back-end
> Store payment

- src/Components/Manager/UserManagement/SideViewUser.js
- src/Components/Manager/UserManagement/UserManagemementGrid.js
- src/Pages/Manager/ManagerView.js
- src/Pages/Manager/UserManagement.js
- src/__tests__/Components/Manager/UserManagemementGrid.test.js
User management on the manager menu
Need PR https://github.com/Hello-Kitchen/Back-End/pull/129 in the back
Try the full CRUD on a user.
Also try to edit a user's password.
Closes #111 
> feat: implement user management functionality with user grid and side view

- src/Components/CurrentCommand/CurrentCommand.js
- src/Components/FoodElem/FoodElem.js
- src/Components/FoodElem/FoodFooter/FoodFooter.js
- src/Components/FoodList/FoodList.js
- src/Pages/Dashboard/Dashboard.js
- src/Pages/Layout.js
- src/Pages/PosRouter.js
- src/__tests__/Components/CurrentCommand.test.js
- src/__tests__/Components/FoodElem/FoodFooter.test.js
- tailwind.config.js
Added new buttons for each foods, used to either increase or decrease the quantity of a food, and a button used to modify the food itself
Add a food to the order. Click on the food name on the right, buttons should appear. Clicking on "+" will increase food quantity. Clicking on "-" will decrease quantity, and if 0 is reached, will remove food from the order. Clicking on "Modifier" will take yo to that food page, with the choices already made. Change the choices, click on "Modifier" (at the bottom of the screen), the food will update.
#102 
> feat: Current order is now editable

- src/Components/CurrentCommand/CurrentCommand.js
Fix the bug whe same food was displayed multiple times instead of one time with the correct quantity
The foods are grouped between each stop and not as a whole
Connect to the POS
Make an order with duplicate foods
Closes #106 
> 106 display right quantity in order

- src/Components/TablesView/TablesPanel.js
Added a new button to delete a table.
Go to the table page, and add a table. In edit mode, select the table, and click on "Supprimer" button.
Closes #143 
> New button in Edit mode of a table, can now delete it

- src/Pages/Loading/Loading.js
- src/Pages/PosRouter.js
The loading page now also loads the table configuration of the current restaurant.
Be sure to have the latest version of the back-end.
Create a pos_config document for the restaurant, then start the POS app. The table page now shows the tables of the document.
Closes #91
> add: loads the saved table config whhen loading the app

- src/Components/CurrentCommand/CurrentCommand.js
- src/Components/TablesView/TablesView.js
- src/Pages/PosRouter.js
Add ID in the table object in addition to the name.
Also, add the table board to the cache
Note: A table name MUST BE a number for now.
Create a table ans save, check if the ID appears in the DB.
Try to reload the page, nothing should have changed.
Closes #147 
Closes #148 
> 147 table id in the pos config

- src/Components/CurrentCommand/CurrentCommand.js
- src/Components/FoodElem/FoodFooter/FoodFooter.js
- src/Components/FoodList/FoodList.js
- src/Components/LayoutFooter/ModalNewOrder.js
- src/Components/TablesView/DroppableTable.js
- src/Components/TablesView/TablesPanel.js
- src/Components/TablesView/TablesView.js
- src/Pages/Dashboard/Dashboard.js
- src/Pages/Layout.js
- src/Pages/PosRouter.js
- src/__tests__/Components/CurrentCommand.test.js
- src/__tests__/Components/ModalNewOrder.test.js
Update orders structure to use objects instead of arrays
Try the application top to bottom, everything should works as intended.
Closes #128 
> refactor: update orders structure to use objects instead of arrays

- src/Components/TablesView/TablesFooter.js
- src/Components/TablesView/TablesPanel.js
- src/Components/TablesView/TablesView.js
- src/Pages/Loading/Loading.js
Added dynamic loading on display of the table board
Added dynamic saving of modifications made on the table board
1. Display the tables
2. Edit the tables in the DB
3. Close tables tab and display it again -> Modifications should appear without reloading
4. Edit a table (and click the edit button to close the edit mode)
5. Check the DB, modifications should appear
Closes #152 
> feat: add dynamic loading and saving of pos_config

- src/Components/TablesView/DroppableTable.js
- src/__tests__/Components/TableView/DroppableTable.test.js
Change the display of time on tables
Go to the Tables menu to see the time on the tables
(If no table, drag one, make an order on this table, the time should now be displayed in form '00:00'
Closes #155 
> 155 table color if occupied

- src/Components/OrdersView/FilterButton.js
- src/Components/OrdersView/OrderRow.js
- src/Components/OrdersView/OrdersView.js
Add the price of the order on row
Made the list of orders scrollable
Made the page responsive
Connect to the POS
Navigate to Orders Menu and check according to mockup
Closes #170 
> 170 responsive orders menu

- src/Components/CurrentCommand/CurrentCommand.js
rewrite the spread for get the orders into function sendOtherOrder
create a new order with two items split by a stop and send twice
Closes #193 
> Fix 'demander la suite'

- src/Components/CurrentCommand/CurrentCommand.js
Removed the scroll appearing on the page when the order was getting too long
Coonnect to the POS
Make a long order, everything will be contained in a scrollable area
Closes #211 
> 211 remove scroll on the page for big orders

- src/Components/OrdersView/FilterButton.js
- src/Components/OrdersView/OrderRow.js
- src/Components/OrdersView/OrdersView.js
- src/__tests__/Components/OrdersView.test.js
Add the possibility to switch between current and passed orders in ordersView
Go on the OrdersView in POS and click to switch between the types of order
Closes #199 
> 199 order in progressdone button in pos order tab
